#!/usr/sbin/nft -f

define RELAY_LAN_IP = 10.100.128.61

flush ruleset

table ip nat {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        
        # 📝 [转发清单] 这里就是你最直观的“账本”，一行一路，改哪里点哪里
        # hk jinx
        meta l4proto { tcp, udp } th dport 37500 counter dnat to 198.176.54.165:37500
        #meta l4proto { tcp, udp } th dport 37600 counter dnat to 198.176.54.165:37600
        meta l4proto { tcp, udp } th dport 37700 counter dnat to 198.176.54.165:37700
        meta l4proto { tcp, udp } th dport 37800 counter dnat to 198.176.54.165:8388
        #qq.pw
        meta l4proto { tcp, udp } th dport 37810 counter dnat to 198.176.54.165:25073

        #jp t1 
        meta l4proto { tcp, udp } th dport 28388 counter dnat to 198.176.52.172:28388
        meta l4proto { tcp, udp } th dport 47600 counter dnat to 198.176.52.172:37600
        


        #jp t1 $6.48
        meta l4proto { tcp, udp } th dport 47710 counter dnat to 198.176.52.64:8388
        #jp t1 $6.48 -> qq.pw
        meta l4proto { tcp, udp } th dport 47720 counter dnat to 198.176.52.64:25073
        #jp t1 $6.48 -> jp@aaitr ss
        meta l4proto { tcp, udp } th dport 47700 counter dnat to 198.176.52.64:37700
        
        # -> vircs at&t
        meta l4proto { tcp, udp } th dport 37600 counter dnat to 198.176.52.64:37600
      

    }

    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        
        # 🛡️ [通用 SNAT] 只要不是发往内网的流量，统一做伪装
        # 这样你上面加多少个新 IP，这里都不用改
        ip daddr != { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } counter snat to $RELAY_LAN_IP
    }
}

table ip filter {
    chain forward {
        type filter hook forward priority 0; policy accept;
        tcp flags syn tcp option maxseg size set 1452 counter
    }
